# Site settings
title: "Luis Carlos Barbieri"
email: 
description: "Site oficial do violonista e compositor Luis Carlos Barbieri"
baseurl: ""
url: "https://luiscarlosbarbieri.com.br"
repo: "http://github.com/jamfreire/luiscarlosbarbieri"
comments: false
author: "Jam Freire"

# Build settings
markdown: kramdown
permalink: /:title
exclude:
  - .jekyll-cache

collections:
    albuns:
      output: true
      permalink: /album/:name
      order:
        - melodia-sentimental.md
        - barbieri-schneiter-solo.md
        - duo-barbieri-schneiter-interpreta.md
        - duo-barbieri-schneiter-10-anos.md
        - duo-barbieri-schneiter-no-caraca.md
        - oitis.md
    biografias:
      output: true
      permalink: /:name
