# Site settings
title: "Luis Carlos Barbieri"
email: 
description: "Site oficial do violonista e compositor Luis Carlos Barbieri"
baseurl: ""
url: "http://jamfreire.github.io/luiscarlosbarbieri"
repo: http://github.com/jamfreire/luiscarlosbarbieri
comments: false
author:
  name: "Jam Freire"

# Build settings
markdown: kramdown
permalink: /:title

collections:
    albuns:
      output: true
      permalink: /album/:name
      order:
        - oitis.md
        - barbieri-schneiter-solo.md
    biografias:
      output: true
      permalink: /:name